title: Martín Morando
description: "Martín Morando, fundador de criptowiki. Proyectos, experimentos y blog. Estudiante Lic. en Gestión de Negocios, ITBA."
url: https://martinmorando.com
language: es
baseurl: ''
image: 'assets/img/icons/m.png?v=2'

permalink: /:title

social:
  github: martinmorando

defaults:
  - scope:
      path: '_posts'
    values:
      layout: 'post'

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false
  ignore:
    envs: [development]

include: [CNAME]
exclude: [martinmorando.gemspec]